name: legit
version: 0.2.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
description: Sane Git Library
homepage: https://github.com/SpinlockLabs/legit/
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  path: "^1.6.2"
  crypto: "^2.0.6"
