name: legit
version: 0.1.0
authors:
- Kenneth Endfinger <kaendfinger@gmail.com>
- samrg472 <samrg472@gmail.com>
- TheMike <zeusintraining@gmail.com>
description: Sane Git Library
homepage: https://github.com/DirectMyFile/legit/
environment:
  sdk: ">=1.13.0"
dependencies:
  path: "^1.3.9"
  crypto: "^0.9.1"
  diff_match_patch: "^0.2.1"
